import { Ingredient, Office, DailyEntry } from './types';

// Single Entity for the entire app
export const OFFICES: Office[] = [
  { id: 'canteen_main', name: 'ACI Center Canteen', location: 'Tejgaon HQ' }
];

export const INGREDIENTS: Ingredient[] = [
  { id: 'ing_01', name: 'Aerometic (পোলাও চাল)', unit: 'kg', unitPrice: 115.00, currentStock: 200, minStockThreshold: 50 },
  { id: 'ing_02', name: 'Miniket Rice (মিনিকেট চাল)', unit: 'kg', unitPrice: 77.00, currentStock: 800, minStockThreshold: 100 },
  { id: 'ing_03', name: 'Mutton (মাটন-খাসীর মাংস)', unit: 'kg', unitPrice: 900.00, currentStock: 40, minStockThreshold: 10 },
  { id: 'ing_04', name: 'Chicken_Sonalika (সোনালিকা)', unit: 'pcs', unitPrice: 220.00, currentStock: 60, minStockThreshold: 20 },
  { id: 'ing_05', name: 'Chicken_Broiler (ব্রয়লার)', unit: 'kg', unitPrice: 300.00, currentStock: 150, minStockThreshold: 40 },
  { id: 'ing_06', name: 'Fish_Rui (রুই মাছ)', unit: 'kg', unitPrice: 350.00, currentStock: 60, minStockThreshold: 15 },
  { id: 'ing_07', name: 'Fish_Pabda/Ilish (পাবদা/ইলিশ)', unit: 'kg', unitPrice: 380.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_08', name: 'Egg (ডিম)', unit: 'pcs', unitPrice: 12.00, currentStock: 1200, minStockThreshold: 200 },
  { id: 'ing_09', name: 'Sorishar Oil (সরিষার তেল)', unit: 'kg', unitPrice: 208.00, currentStock: 40, minStockThreshold: 10 },
  { id: 'ing_10', name: 'Oil (Soybean) (সয়াবিন তেল)', unit: 'kg', unitPrice: 170.40, currentStock: 100, minStockThreshold: 20 },
  { id: 'ing_11', name: 'Dall_Moshur (মশুর ডাল)', unit: 'kg', unitPrice: 90.00, currentStock: 150, minStockThreshold: 30 },
  { id: 'ing_12', name: 'Dal_Boot (বুট)', unit: 'kg', unitPrice: 130.00, currentStock: 50, minStockThreshold: 10 },
  { id: 'ing_13', name: 'Dal_Mug (মুগ ডাল)', unit: 'kg', unitPrice: 125.22, currentStock: 50, minStockThreshold: 10 },
  { id: 'ing_14', name: 'Ghee (ঘী)', unit: 'kg', unitPrice: 1270.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_15', name: 'Butter (বাটার)', unit: 'pcs', unitPrice: 135.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_16', name: 'Tok Doi (টক দই)', unit: 'kg', unitPrice: 220.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_17', name: 'Chili Powder (মরিচের গুড়া)', unit: 'kg', unitPrice: 346.00, currentStock: 15, minStockThreshold: 5 },
  { id: 'ing_18', name: 'Turmeric Powder (হলুদের গুড়া)', unit: 'kg', unitPrice: 300.00, currentStock: 15, minStockThreshold: 5 },
  { id: 'ing_19', name: 'Coriander Powder (ধনিয়া গুড়া)', unit: 'kg', unitPrice: 208.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_20', name: 'Dry Chili (শুকনা মরিচ)', unit: 'kg', unitPrice: 348.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_21', name: 'Jira (জিরা)', unit: 'kg', unitPrice: 696.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_22', name: 'Shahi Jera (শাহী জিরা)', unit: 'kg', unitPrice: 1520.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_23', name: 'Elachi (এলাচ)', unit: 'kg', unitPrice: 5296.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_24', name: 'Daruchini (দারুচিনি)', unit: 'kg', unitPrice: 544.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_25', name: 'Jaitrik (জৈত্রিক)', unit: 'kg', unitPrice: 3660.00, currentStock: 1, minStockThreshold: 0.2 },
  { id: 'ing_26', name: 'Joy Fal (জয়ফল)', unit: 'kg', unitPrice: 1040.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_27', name: 'Lobonga (লবঙ্গ)', unit: 'kg', unitPrice: 1570.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_28', name: 'Posto Dana (পোস্তদানা)', unit: 'kg', unitPrice: 4600.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_29', name: 'Alu Bokhara (আলু বোখরা)', unit: 'kg', unitPrice: 1000.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_30', name: 'Kismis (কিছমিছ)', unit: 'kg', unitPrice: 1000.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_31', name: 'Tejpata (তেজপাতা)', unit: 'kg', unitPrice: 200.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_32', name: 'Tomato Sauce (টমেটো সস)', unit: 'kg', unitPrice: 270.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_33', name: 'Soya Sauce (সয়া সস)', unit: 'pcs', unitPrice: 120.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_34', name: 'Fish Sauce (ফিস সস)', unit: 'bottle', unitPrice: 220.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_35', name: 'Salt (লবণ)', unit: 'kg', unitPrice: 42.00, currentStock: 100, minStockThreshold: 20 },
  { id: 'ing_36', name: 'Black Pepper (কালো গোল মরিচ)', unit: 'kg', unitPrice: 1307.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_37', name: 'White Pepper (সাদা গোল মরিচ)', unit: 'kg', unitPrice: 1699.00, currentStock: 2, minStockThreshold: 0.5 },
  { id: 'ing_38', name: 'Almonds (কাঠ বাদাম)', unit: 'kg', unitPrice: 2000.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_39', name: 'Cashew Nuts (কাজু বাদাম)', unit: 'kg', unitPrice: 1250.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_40', name: 'Peanuts (চীনা বাদাম)', unit: 'kg', unitPrice: 203.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_41', name: 'Milk Powder (দুধের পাওডার)', unit: 'kg', unitPrice: 880.00, currentStock: 10, minStockThreshold: 2 },
  { id: 'ing_42', name: 'Panch Foron (পাঁচ ফোড়ণ)', unit: 'kg', unitPrice: 305.00, currentStock: 5, minStockThreshold: 1 },
  { id: 'ing_43', name: 'Potato (আলু)', unit: 'kg', unitPrice: 28.00, currentStock: 300, minStockThreshold: 50 },
  { id: 'ing_44', name: 'Onion (পিয়াজ)', unit: 'kg', unitPrice: 110.00, currentStock: 200, minStockThreshold: 40 },
  { id: 'ing_45', name: 'Garlic (রসুন)', unit: 'kg', unitPrice: 180.00, currentStock: 50, minStockThreshold: 10 },
  { id: 'ing_46', name: 'Ginger (জিঞ্জার)', unit: 'kg', unitPrice: 230.00, currentStock: 50, minStockThreshold: 10 },
  { id: 'ing_47', name: 'Green Chili (কাঁচা মরিচ)', unit: 'kg', unitPrice: 100.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_48', name: 'Cucumber (শসা)', unit: 'kg', unitPrice: 45.00, currentStock: 40, minStockThreshold: 10 },
  { id: 'ing_49', name: 'Lemon (লেবু)', unit: 'pcs', unitPrice: 9.00, currentStock: 200, minStockThreshold: 50 },
  { id: 'ing_50', name: 'Coriander Leaf (ধনিয়া পাতা)', unit: 'pcs', unitPrice: 80.00, currentStock: 20, minStockThreshold: 5 },
  { id: 'ing_51', name: 'Vegetable (Mixed)', unit: 'kg', unitPrice: 70.00, currentStock: 100, minStockThreshold: 20 },
  { id: 'ing_52', name: 'Beef', unit: 'kg', unitPrice: 720.00, currentStock: 80, minStockThreshold: 20 },
  { id: 'ing_53', name: 'Mint Leaf (পুদিনা পাতা)', unit: 'kg', unitPrice: 200.00, currentStock: 5, minStockThreshold: 1 },
];
